#!/bin/bash
tmpfile=$HOME/code.txt

if [ "$#" -eq "1" ]; then
        tmpfile=$HOME/code.$1
fi

rm -f $tmpfile

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

cat $input >> $tmpfile

code -r $tmpfile

rm $tmpfile
